### ISSUE TITLE
Potential Dupe & Money Glitch

### ISSUE THREAD

**Issue by BahZuka** [IamLation/lation_pawnshop#4]
when selling a item u get from metal detecting you can drag the item your selling onto a item that is already in there and you get the item that is in the pawn shop already
you can just keep swapping items basically

**Comment by IamLation** [comment]
There's currently a couple issues I'm trying to work out, some of which are items with stack = false and degraded durability levels that are causing issues. I need a bit more information and data regarding this issue to identify if its the same issue or a new one.

**Comment by IamLation** [comment]
This was resolved
