### ISSUE TITLE
Selling a extra item

### ISSUE THREAD

**Issue by meetbilllol** [IamLation/lation_pawnshop#7]
Not sure its a me issue with ox inventory i set the inventory to 1 then i drag 1 lock pick over to the pawn shop i comes up saying do you want to sell 1x lock pick i click confirm and i recive money for 1 lockpick and it takes 2 lock picks

**Comment by IamLation** [comment]
Leave it at 0 if you want to sell just 1

**Comment by Legacy-TacticalGamingInteractive** [comment]
On this topic some people are saying they can sell over 1000 items and get rich af.
Do you know if there is a way to limit how much someone get sell in total that day?

**Comment by IamLation** [comment]
There are not currently any limits in place. I would recommend that if you're aware of players with an abundance of certain item(s) then price them accordingly. Same can be said about easily accessible items. It's always a balancing act - putting a limit in place doesn't really solve the root issue, they would still get rich af, it would just happen slightly slower. Wouldn't be too difficult to implement a per-session limit but besides it not being a real solution to the aforementioned issue and rather just a band aid, I'm also not sure how far I plan to go with this script.

**Comment by uncfromtsrp** [comment]
Hi, I'm experiencing this as well when the player has 2 separate stacks of the same item in their inventory. It will remove the item to be sold from both stacks but only pay out for 1.

**Comment by IamLation** [comment]
Was fixed
