### ISSUE TITLE
2 stacks of same item when selling will remove specified amount from both stacks

### ISSUE THREAD

**Issue by uncfromtsrp** [IamLation/lation_pawnshop#8]
If you have 2 separate stacks of the same item say 25 gold bars and 10 gold bars, and drag 5 over to be sold, then it will remove 5 items from both stacks but only pay you for the intended 5. 

Player gets paid for 5 gold bars, but lost 10 and ends up with a stack of 20 and stack of 5.

**Comment by IamLation** [comment]
Was fixed
